### ISSUE TITLE
헤더 이벤트(?)

### ISSUE THREAD

**Issue by syxxn** [EntryDSM/Genesis#33]
![image](https://user-images.githubusercontent.com/64132926/178386092-5e67cd6c-c7ab-4dfa-966c-0e4a284e6669.png)
![image](https://user-images.githubusercontent.com/64132926/178386108-519b97d6-31f8-4236-9229-316e5d60227a.png)

왜 로그아웃은 커서를 가져다 놔도 애니메이션이 없는거야?

**Comment by hxxnim** [comment]
로그아웃은 다른 버튼이랑 일부러 구분해둔거임
